import type {
  MockTest,
  ExamNotification,
  LeaderboardEntry,
  AnalyticsData,
  User,
  Question,
} from "../interfaces";

export const CURRENT_USER: User = {
  id: "u1",
  name: "Anil Kumar",
  email: "anil@example.com",
  phone: "9876543210",
  category: "SC",
  targetExam: "RRB NTPC",
  subscriptionPlan: "monthly",
  joinedAt: "2024-01-15",
  testsAttempted: 24,
  averageScore: 71,
  rank: 142,
};

export const MOCK_TESTS: MockTest[] = [
  {
    id: "mt1",
    title: "RRB NTPC Full Mock Test #1",
    exam: "RRB NTPC",
    duration: 90,
    totalQuestions: 100,
    subjects: ["maths", "reasoning", "gk"],
    difficulty: "medium",
    negativeMarking: true,
    negativeMarkValue: 0.33,
    isAttempted: true,
    bestScore: 68,
    createdAt: "2024-01-10",
    totalAttempts: 12450,
  },
  {
    id: "mt2",
    title: "RRB NTPC Full Mock Test #2",
    exam: "RRB NTPC",
    duration: 90,
    totalQuestions: 100,
    subjects: ["maths", "reasoning", "gk"],
    difficulty: "hard",
    negativeMarking: true,
    negativeMarkValue: 0.33,
    isAttempted: false,
    createdAt: "2024-01-15",
    totalAttempts: 9320,
  },
  {
    id: "mt3",
    title: "RRB NTPC Maths Sectional Test",
    exam: "RRB NTPC",
    duration: 30,
    totalQuestions: 30,
    subjects: ["maths"],
    difficulty: "medium",
    negativeMarking: true,
    negativeMarkValue: 0.33,
    isAttempted: true,
    bestScore: 75,
    createdAt: "2024-01-20",
    totalAttempts: 18900,
  },
  {
    id: "mt4",
    title: "RRB Group D Full Mock Test #1",
    exam: "RRB Group D",
    duration: 90,
    totalQuestions: 100,
    subjects: ["maths", "reasoning", "gk", "technical"],
    difficulty: "easy",
    negativeMarking: true,
    negativeMarkValue: 0.33,
    isAttempted: false,
    createdAt: "2024-02-01",
    totalAttempts: 7600,
  },
  {
    id: "mt5",
    title: "RRB NTPC Reasoning Sectional Test",
    exam: "RRB NTPC",
    duration: 30,
    totalQuestions: 30,
    subjects: ["reasoning"],
    difficulty: "medium",
    negativeMarking: true,
    negativeMarkValue: 0.33,
    isAttempted: true,
    bestScore: 80,
    createdAt: "2024-02-05",
    totalAttempts: 15200,
  },
  {
    id: "mt6",
    title: "RRB NTPC GK & Current Affairs Test",
    exam: "RRB NTPC",
    duration: 30,
    totalQuestions: 40,
    subjects: ["gk"],
    difficulty: "hard",
    negativeMarking: true,
    negativeMarkValue: 0.33,
    isAttempted: false,
    createdAt: "2024-02-10",
    totalAttempts: 6800,
  },
  {
    id: "mt7",
    title: "RRB JE Technical Mock Test",
    exam: "RRB JE",
    duration: 120,
    totalQuestions: 150,
    subjects: ["maths", "reasoning", "gk", "technical"],
    difficulty: "hard",
    negativeMarking: true,
    negativeMarkValue: 0.33,
    isAttempted: false,
    createdAt: "2024-02-15",
    totalAttempts: 4200,
  },
  {
    id: "mt8",
    title: "RRB NTPC Previous Year 2022 Paper",
    exam: "RRB NTPC",
    duration: 90,
    totalQuestions: 100,
    subjects: ["maths", "reasoning", "gk"],
    difficulty: "medium",
    negativeMarking: true,
    negativeMarkValue: 0.33,
    isAttempted: true,
    bestScore: 72,
    createdAt: "2024-02-20",
    totalAttempts: 21000,
  },
];

export const SAMPLE_QUESTIONS: Question[] = [
  {
    id: "q1",
    exam: "RRB NTPC",
    year: 2022,
    subject: "maths",
    topic: "Percentage",
    questionText: "A shopkeeper marks his goods at 25% above cost price and gives 10% discount. What is his profit percentage?",
    options: ["12.5%", "15%", "10%", "8.5%"],
    correctAnswer: 0,
    explanation: "Let CP = 100. MP = 125. SP after 10% discount = 125 × 0.9 = 112.5. Profit% = (112.5 - 100)/100 × 100 = 12.5%",
    difficulty: "medium",
    language: "en",
  },
  {
    id: "q2",
    exam: "RRB NTPC",
    year: 2022,
    subject: "reasoning",
    topic: "Number Series",
    questionText: "What is the next number in the series: 2, 6, 12, 20, 30, ?",
    options: ["40", "42", "44", "46"],
    correctAnswer: 1,
    explanation: "Differences: 4, 6, 8, 10, 12. Next = 30 + 12 = 42",
    difficulty: "easy",
    language: "en",
  },
  {
    id: "q3",
    exam: "RRB NTPC",
    year: 2021,
    subject: "gk",
    topic: "Indian Railways",
    questionText: "Which is the longest railway platform in India?",
    options: ["Gorakhpur", "Kollam", "Kharagpur", "Patna"],
    correctAnswer: 0,
    explanation: "Gorakhpur railway station in Uttar Pradesh has the world's longest railway platform at 1366.33 meters.",
    difficulty: "easy",
    language: "en",
  },
  {
    id: "q4",
    exam: "RRB NTPC",
    year: 2022,
    subject: "maths",
    topic: "Simple Interest",
    questionText: "Find the simple interest on ₹5000 at 8% per annum for 3 years.",
    options: ["₹1200", "₹1000", "₹1500", "₹800"],
    correctAnswer: 0,
    explanation: "SI = P × R × T / 100 = 5000 × 8 × 3 / 100 = ₹1200",
    difficulty: "easy",
    language: "en",
  },
  {
    id: "q5",
    exam: "RRB NTPC",
    year: 2022,
    subject: "reasoning",
    topic: "Coding-Decoding",
    questionText: "If COMPUTER is coded as RFUVQNPC, then how is PRINTER coded?",
    options: ["QSJOUFS", "SFUOJSQ", "SFUQJSQ", "QSJOSUF"],
    correctAnswer: 0,
    explanation: "Each letter is coded as the next letter in the alphabet. P→Q, R→S, I→J, N→O, T→U, E→F, R→S = QSJOUFS",
    difficulty: "hard",
    language: "en",
  },
];

export const EXAM_NOTIFICATIONS: ExamNotification[] = [
  {
    id: "n1",
    title: "RRB NTPC CEN 05/2024 – 11,558 Vacancies",
    examType: "RRB NTPC",
    vacancyCount: 11558,
    categoryWiseVacancy: { UR: 5330, SC: 1734, ST: 867, OBC: 3121, EWS: 506 },
    applyStart: "2024-09-14",
    applyEnd: "2024-10-13",
    examDate: "2025-03-01",
    officialLink: "https://www.rrbcdg.gov.in",
    postedAt: "2024-09-10",
    isNew: true,
    status: "active",
  },
  {
    id: "n2",
    title: "RRB Group D CEN 02/2025 – 32,438 Vacancies",
    examType: "RRB Group D",
    vacancyCount: 32438,
    categoryWiseVacancy: { UR: 14920, SC: 4865, ST: 2435, OBC: 8758, EWS: 1460 },
    applyStart: "2025-01-23",
    applyEnd: "2025-02-22",
    examDate: "2025-06-01",
    officialLink: "https://www.rrbcdg.gov.in",
    postedAt: "2025-01-20",
    isNew: true,
    status: "active",
  },
  {
    id: "n3",
    title: "RRB JE (Junior Engineer) CEN 03/2024",
    examType: "RRB JE",
    vacancyCount: 7951,
    categoryWiseVacancy: { UR: 3660, SC: 1194, ST: 596, OBC: 2144, EWS: 357 },
    applyStart: "2024-07-30",
    applyEnd: "2024-08-29",
    examDate: "2024-12-01",
    resultDate: "2025-02-15",
    officialLink: "https://www.rrbcdg.gov.in",
    postedAt: "2024-07-25",
    isNew: false,
    status: "result_declared",
  },
  {
    id: "n4",
    title: "RRB ALP & Technician CEN 01/2025",
    examType: "RRB ALP",
    vacancyCount: 9144,
    categoryWiseVacancy: { UR: 4210, SC: 1371, ST: 686, OBC: 2469, EWS: 408 },
    applyStart: "2025-02-10",
    applyEnd: "2025-03-11",
    officialLink: "https://www.rrbcdg.gov.in",
    postedAt: "2025-02-05",
    isNew: true,
    status: "upcoming",
  },
];

export const LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, userId: "u10", name: "Ravi Teja Sharma", category: "OBC", testsAttempted: 45, averageScore: 92, totalPoints: 4140, badge: "gold" },
  { rank: 2, userId: "u11", name: "Priya Devi", category: "SC", testsAttempted: 42, averageScore: 89, totalPoints: 3738, badge: "gold" },
  { rank: 3, userId: "u12", name: "Suresh Kumar", category: "UR", testsAttempted: 50, averageScore: 87, totalPoints: 4350, badge: "gold" },
  { rank: 4, userId: "u13", name: "Lakshmi Narayana", category: "OBC", testsAttempted: 38, averageScore: 85, totalPoints: 3230, badge: "silver" },
  { rank: 5, userId: "u14", name: "Ganesh Babu", category: "ST", testsAttempted: 40, averageScore: 83, totalPoints: 3320, badge: "silver" },
  { rank: 6, userId: "u15", name: "Anitha Reddy", category: "SC", testsAttempted: 35, averageScore: 81, totalPoints: 2835, badge: "silver" },
  { rank: 7, userId: "u16", name: "Venkat Rao", category: "UR", testsAttempted: 30, averageScore: 79, totalPoints: 2370, badge: "bronze" },
  { rank: 8, userId: "u17", name: "Sita Devi", category: "OBC", testsAttempted: 28, averageScore: 77, totalPoints: 2156, badge: "bronze" },
  { rank: 9, userId: "u18", name: "Ramesh Naidu", category: "SC", testsAttempted: 32, averageScore: 75, totalPoints: 2400, badge: "bronze" },
  { rank: 10, userId: "u19", name: "Deepa Kumari", category: "EWS", testsAttempted: 25, averageScore: 74, totalPoints: 1850, badge: "none" },
  { rank: 142, userId: "u1", name: "Anil Kumar (You)", category: "SC", testsAttempted: 24, averageScore: 71, totalPoints: 1704, badge: "none" },
];

export const ANALYTICS_DATA: AnalyticsData = {
  subjectWise: [
    { subject: "Mathematics", score: 68, total: 100, percentage: 68 },
    { subject: "Reasoning", score: 78, total: 100, percentage: 78 },
    { subject: "General Knowledge", score: 65, total: 100, percentage: 65 },
    { subject: "Technical", score: 55, total: 100, percentage: 55 },
  ],
  topicWise: [
    { topic: "Number Series", correct: 18, total: 20 },
    { topic: "Percentage", correct: 14, total: 20 },
    { topic: "Simple Interest", correct: 16, total: 20 },
    { topic: "Coding-Decoding", correct: 12, total: 20 },
    { topic: "Indian History", correct: 10, total: 20 },
    { topic: "Current Affairs", correct: 8, total: 20 },
    { topic: "Geometry", correct: 9, total: 20 },
    { topic: "Blood Relations", correct: 15, total: 20 },
  ],
  recentTests: [
    { date: "Feb 28", score: 72, name: "Mock Test #1" },
    { date: "Feb 25", score: 68, name: "Maths Sectional" },
    { date: "Feb 22", score: 75, name: "Reasoning Test" },
    { date: "Feb 19", score: 61, name: "GK Test" },
    { date: "Feb 16", score: 70, name: "Mock Test #2" },
    { date: "Feb 13", score: 66, name: "Full Mock" },
  ],
  weeklyActivity: [
    { day: "Mon", questions: 45, time: 60 },
    { day: "Tue", questions: 30, time: 40 },
    { day: "Wed", questions: 60, time: 80 },
    { day: "Thu", questions: 20, time: 30 },
    { day: "Fri", questions: 75, time: 90 },
    { day: "Sat", questions: 100, time: 120 },
    { day: "Sun", questions: 50, time: 65 },
  ],
  accuracy: 71,
  averageTime: 52,
  strongTopics: ["Number Series", "Blood Relations", "Simple Interest"],
  weakTopics: ["Current Affairs", "Indian History", "Geometry"],
};

export const SUBSCRIPTION_PLANS = [
  {
    id: "free",
    name: "Free",
    price: 0,
    duration: "Forever",
    features: [
      "1 Mock Test per week",
      "Basic PYQ access (50 questions)",
      "Exam Notifications",
      "Community Forum access",
      "Limited Analytics",
    ],
    isPopular: false,
  },
  {
    id: "monthly",
    name: "Monthly",
    price: 199,
    duration: "per month",
    features: [
      "Unlimited Mock Tests",
      "Full PYQ bank (5000+ questions)",
      "Performance Analytics",
      "SC/ST/OBC Guidance",
      "Study Planner",
      "Leaderboard access",
      "Ad-free experience",
      "Priority support",
    ],
    isPopular: true,
    badge: "Most Popular",
  },
  {
    id: "quarterly",
    name: "Quarterly",
    price: 499,
    duration: "per 3 months",
    features: [
      "Everything in Monthly",
      "Save ₹98 vs Monthly",
      "Advanced Analytics",
      "Doubt clearing sessions",
      "Downloadable notes",
    ],
    isPopular: false,
    badge: "Save 17%",
  },
  {
    id: "annual",
    name: "Annual",
    price: 999,
    duration: "per year",
    features: [
      "Everything in Quarterly",
      "Save ₹1389 vs Monthly",
      "1-on-1 mentorship session",
      "Mock interview preparation",
      "Physical study material",
      "Exam day support",
    ],
    isPopular: false,
    badge: "Best Value",
  },
];

export const PYQ_TOPICS = [
  { subject: "maths", topic: "Percentage", count: 145 },
  { subject: "maths", topic: "Simple Interest & Compound Interest", count: 132 },
  { subject: "maths", topic: "Ratio & Proportion", count: 118 },
  { subject: "maths", topic: "Number System", count: 108 },
  { subject: "maths", topic: "Time & Work", count: 95 },
  { subject: "maths", topic: "Speed, Distance & Time", count: 88 },
  { subject: "maths", topic: "Profit & Loss", count: 82 },
  { subject: "maths", topic: "Geometry & Mensuration", count: 76 },
  { subject: "reasoning", topic: "Number Series", count: 156 },
  { subject: "reasoning", topic: "Coding-Decoding", count: 143 },
  { subject: "reasoning", topic: "Blood Relations", count: 128 },
  { subject: "reasoning", topic: "Analogies", count: 115 },
  { subject: "reasoning", topic: "Direction Sense", count: 98 },
  { subject: "reasoning", topic: "Seating Arrangement", count: 87 },
  { subject: "gk", topic: "Indian Railways", count: 178 },
  { subject: "gk", topic: "Indian History", count: 165 },
  { subject: "gk", topic: "Indian Geography", count: 142 },
  { subject: "gk", topic: "Current Affairs", count: 198 },
  { subject: "gk", topic: "Indian Economy", count: 125 },
  { subject: "gk", topic: "Science & Technology", count: 112 },
];
