/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutSubscriptionRouteImport } from './routes/_layout/subscription'
import { Route as LayoutReservationRouteImport } from './routes/_layout/reservation'
import { Route as LayoutPyqRouteImport } from './routes/_layout/pyq'
import { Route as LayoutPlannerRouteImport } from './routes/_layout/planner'
import { Route as LayoutNotificationsRouteImport } from './routes/_layout/notifications'
import { Route as LayoutMockTestsRouteImport } from './routes/_layout/mock-tests'
import { Route as LayoutLeaderboardRouteImport } from './routes/_layout/leaderboard'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutAnalyticsRouteImport } from './routes/_layout/analytics'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutTakeTestTestIdRouteImport } from './routes/_layout/take-test.$testId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSubscriptionRoute = LayoutSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReservationRoute = LayoutReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPyqRoute = LayoutPyqRouteImport.update({
  id: '/pyq',
  path: '/pyq',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlannerRoute = LayoutPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNotificationsRoute = LayoutNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMockTestsRoute = LayoutMockTestsRouteImport.update({
  id: '/mock-tests',
  path: '/mock-tests',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLeaderboardRoute = LayoutLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyticsRoute = LayoutAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTakeTestTestIdRoute = LayoutTakeTestTestIdRouteImport.update({
  id: '/take-test/$testId',
  path: '/take-test/$testId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof LayoutAdminRoute
  '/analytics': typeof LayoutAnalyticsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/leaderboard': typeof LayoutLeaderboardRoute
  '/mock-tests': typeof LayoutMockTestsRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/planner': typeof LayoutPlannerRoute
  '/pyq': typeof LayoutPyqRoute
  '/reservation': typeof LayoutReservationRoute
  '/subscription': typeof LayoutSubscriptionRoute
  '/take-test/$testId': typeof LayoutTakeTestTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof LayoutAdminRoute
  '/analytics': typeof LayoutAnalyticsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/leaderboard': typeof LayoutLeaderboardRoute
  '/mock-tests': typeof LayoutMockTestsRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/planner': typeof LayoutPlannerRoute
  '/pyq': typeof LayoutPyqRoute
  '/reservation': typeof LayoutReservationRoute
  '/subscription': typeof LayoutSubscriptionRoute
  '/take-test/$testId': typeof LayoutTakeTestTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/analytics': typeof LayoutAnalyticsRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/leaderboard': typeof LayoutLeaderboardRoute
  '/_layout/mock-tests': typeof LayoutMockTestsRoute
  '/_layout/notifications': typeof LayoutNotificationsRoute
  '/_layout/planner': typeof LayoutPlannerRoute
  '/_layout/pyq': typeof LayoutPyqRoute
  '/_layout/reservation': typeof LayoutReservationRoute
  '/_layout/subscription': typeof LayoutSubscriptionRoute
  '/_layout/take-test/$testId': typeof LayoutTakeTestTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/leaderboard'
    | '/mock-tests'
    | '/notifications'
    | '/planner'
    | '/pyq'
    | '/reservation'
    | '/subscription'
    | '/take-test/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/leaderboard'
    | '/mock-tests'
    | '/notifications'
    | '/planner'
    | '/pyq'
    | '/reservation'
    | '/subscription'
    | '/take-test/$testId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/register'
    | '/_layout/admin'
    | '/_layout/analytics'
    | '/_layout/dashboard'
    | '/_layout/leaderboard'
    | '/_layout/mock-tests'
    | '/_layout/notifications'
    | '/_layout/planner'
    | '/_layout/pyq'
    | '/_layout/reservation'
    | '/_layout/subscription'
    | '/_layout/take-test/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/subscription': {
      id: '/_layout/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof LayoutSubscriptionRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reservation': {
      id: '/_layout/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof LayoutReservationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pyq': {
      id: '/_layout/pyq'
      path: '/pyq'
      fullPath: '/pyq'
      preLoaderRoute: typeof LayoutPyqRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/planner': {
      id: '/_layout/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof LayoutPlannerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notifications': {
      id: '/_layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof LayoutNotificationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mock-tests': {
      id: '/_layout/mock-tests'
      path: '/mock-tests'
      fullPath: '/mock-tests'
      preLoaderRoute: typeof LayoutMockTestsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/leaderboard': {
      id: '/_layout/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LayoutLeaderboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analytics': {
      id: '/_layout/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof LayoutAnalyticsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/take-test/$testId': {
      id: '/_layout/take-test/$testId'
      path: '/take-test/$testId'
      fullPath: '/take-test/$testId'
      preLoaderRoute: typeof LayoutTakeTestTestIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAnalyticsRoute: typeof LayoutAnalyticsRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutLeaderboardRoute: typeof LayoutLeaderboardRoute
  LayoutMockTestsRoute: typeof LayoutMockTestsRoute
  LayoutNotificationsRoute: typeof LayoutNotificationsRoute
  LayoutPlannerRoute: typeof LayoutPlannerRoute
  LayoutPyqRoute: typeof LayoutPyqRoute
  LayoutReservationRoute: typeof LayoutReservationRoute
  LayoutSubscriptionRoute: typeof LayoutSubscriptionRoute
  LayoutTakeTestTestIdRoute: typeof LayoutTakeTestTestIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAnalyticsRoute: LayoutAnalyticsRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutLeaderboardRoute: LayoutLeaderboardRoute,
  LayoutMockTestsRoute: LayoutMockTestsRoute,
  LayoutNotificationsRoute: LayoutNotificationsRoute,
  LayoutPlannerRoute: LayoutPlannerRoute,
  LayoutPyqRoute: LayoutPyqRoute,
  LayoutReservationRoute: LayoutReservationRoute,
  LayoutSubscriptionRoute: LayoutSubscriptionRoute,
  LayoutTakeTestTestIdRoute: LayoutTakeTestTestIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
